
app:
  name: "myservice-dev"
  version: "dev"
  environment: "development"
  debug: true
  region: "local"
  instance_id: ""

server:
  host: "localhost"
  port: 3000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  shutdown_timeout: "5s"
  
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true
    max_age: 86400

database:
  driver: "postgres"
  host: "0.0.0.0"                # Docker Compose service name
  port: 5432
  name: "myapp_dev"
  user: "postgres"
  password: "devpassword"
  ssl_mode: "disable"
  connect_timeout: "10s"
  max_open_conns: 5
  max_idle_conns: 2
  conn_max_lifetime: "5m"
  conn_max_idle_time: "1m"
  log_slow_queries: true
  slow_query_threshold: "100ms"

logger:
  level: "debug"
  format: "console"
  output: "stdout"
  development: true
  disable_caller: false
  disable_stacktrace: true
  component_logging: true

metrics:
  enabled: false
  type: "mock"                    # Use mock for development
  address: "statsd:8125"          # Docker Compose service name
  prefix: "myapp.dev"
  underlying_type: ""
  buffer_size: 0
  flush_interval: "0s"
  report_interval: "10s"
  tags: []